## The following defaults are set by GitHub, which you are free to override in your _config.yml file:
#github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

## Github config overrides (c.f. https://help.github.com/articles/configuring-jekyll/)
# These are just here to match their configuration
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
