# Github config overrides (c.f. https://help.github.com/articles/using-jekyll-with-pages)
# These are just here to match their configuration
safe: true
lsi: false
pygments: true
#source: /
markdown: kramdown
